/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Juan Carlos
 */
public class JCheckBoxJRadioButton extends javax.swing.JFrame {

    /**
     * Creates new form MiVentanaJCheckBoxJRadioButton
     */
    public JCheckBoxJRadioButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbgroup_sexo = new javax.swing.ButtonGroup();
        text_check = new javax.swing.JLabel();
        Check_futbol = new javax.swing.JCheckBox();
        Check_baloncesto = new javax.swing.JCheckBox();
        Check_Golf = new javax.swing.JCheckBox();
        text_radio = new javax.swing.JLabel();
        rd_hombre = new javax.swing.JRadioButton();
        rd_mujer = new javax.swing.JRadioButton();
        text_nombre = new javax.swing.JLabel();
        campo_nombre = new javax.swing.JTextField();
        text_descripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campo_descripcion = new javax.swing.JTextArea();
        boton_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        text_check.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_check.setText("Intereses");

        Check_futbol.setText("Fútbol");
        Check_futbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check_futbolActionPerformed(evt);
            }
        });

        Check_baloncesto.setText("Baloncesto");

        Check_Golf.setText("Golf");
        Check_Golf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check_GolfActionPerformed(evt);
            }
        });

        text_radio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_radio.setText("Sexo");

        rbgroup_sexo.add(rd_hombre);
        rd_hombre.setText("Hombre");

        rbgroup_sexo.add(rd_mujer);
        rd_mujer.setText("Mujer");

        text_nombre.setText("Nombre");

        text_descripcion.setText("Descripción");

        campo_descripcion.setColumns(20);
        campo_descripcion.setRows(5);
        jScrollPane1.setViewportView(campo_descripcion);
        campo_descripcion.getAccessibleContext().setAccessibleParent(null);

        boton_salir.setText("Salir");
        boton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_descripcion)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rd_mujer)
                                    .addComponent(rd_hombre)
                                    .addComponent(text_radio)
                                    .addComponent(text_check, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Check_Golf)
                                    .addComponent(Check_baloncesto)
                                    .addComponent(Check_futbol))
                                .addGap(21, 21, 21))
                            .addComponent(boton_salir, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(text_nombre)
                    .addComponent(campo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(text_nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text_descripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text_radio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rd_hombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rd_mujer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_check)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Check_futbol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Check_baloncesto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Check_Golf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boton_salir)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Check_GolfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check_GolfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Check_GolfActionPerformed

    private void boton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_salirActionPerformed

    private void Check_futbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check_futbolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Check_futbolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCheckBoxJRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCheckBoxJRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCheckBoxJRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCheckBoxJRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JCheckBoxJRadioButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Check_Golf;
    private javax.swing.JCheckBox Check_baloncesto;
    private javax.swing.JCheckBox Check_futbol;
    private javax.swing.JButton boton_salir;
    private javax.swing.JTextArea campo_descripcion;
    private javax.swing.JTextField campo_nombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup rbgroup_sexo;
    private javax.swing.JRadioButton rd_hombre;
    private javax.swing.JRadioButton rd_mujer;
    private javax.swing.JLabel text_check;
    private javax.swing.JLabel text_descripcion;
    private javax.swing.JLabel text_nombre;
    private javax.swing.JLabel text_radio;
    // End of variables declaration//GEN-END:variables
}
