/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UD6_3_ArrayList;

/**
 *
 * @author Juan Carlos
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        matriculaLb = new javax.swing.JLabel();
        matriculaTf = new javax.swing.JTextField();
        marcaLb = new javax.swing.JLabel();
        marcaTf = new javax.swing.JTextField();
        altaBt = new javax.swing.JButton();
        bajasBt = new javax.swing.JButton();
        mensajeLb = new javax.swing.JLabel();
        modificarBt = new javax.swing.JButton();
        mensajeModificarLb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listadoTa = new javax.swing.JTextArea();
        listadoBt = new javax.swing.JButton();
        buscarBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        matriculaLb.setText("Matrícula");

        marcaLb.setText("Marca");

        altaBt.setText("Alta");
        altaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaBtActionPerformed(evt);
            }
        });

        bajasBt.setText("Bajas");
        bajasBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajasBtActionPerformed(evt);
            }
        });

        modificarBt.setText("Modificar");
        modificarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBtActionPerformed(evt);
            }
        });

        mensajeModificarLb.setText("Para modificar, introducir la matrícula, la nueva marca y pulsar el botón Modificar");

        listadoTa.setColumns(20);
        listadoTa.setRows(5);
        jScrollPane1.setViewportView(listadoTa);

        listadoBt.setText("Listado");
        listadoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoBtActionPerformed(evt);
            }
        });

        buscarBt.setText("Buscar por matrícula");
        buscarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mensajeModificarLb)
                            .addComponent(modificarBt)
                            .addComponent(mensajeLb))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(altaBt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(bajasBt))
                            .addComponent(marcaLb)
                            .addComponent(matriculaLb)
                            .addComponent(matriculaTf)
                            .addComponent(marcaTf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(buscarBt)
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listadoBt)
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(matriculaLb)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(matriculaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarBt))
                        .addGap(26, 26, 26)
                        .addComponent(marcaLb)
                        .addGap(18, 18, 18)
                        .addComponent(marcaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(altaBt)
                            .addComponent(bajasBt))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(mensajeLb)
                .addGap(17, 17, 17)
                .addComponent(listadoBt)
                .addGap(2, 2, 2)
                .addComponent(modificarBt)
                .addGap(18, 18, 18)
                .addComponent(mensajeModificarLb)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listadoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoBtActionPerformed
        /*Objeto fichero sin parámetros (Contiene toda la lectura del fichero)
        mostramos en el listadoTa el texto obtenido en el método listado de la clase fichero*/
        Fichero f = new Fichero();
        this.listadoTa.setText(f.listado());
    }//GEN-LAST:event_listadoBtActionPerformed

    private void altaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaBtActionPerformed
        /*Objeto fichero sin parámetros (Contiene toda la lectura del fichero)
        agregamos la matricula y la marca del textField a nuestro array y guardarlo en el fichero con el metodo altaCoche*/
        Fichero f = new Fichero();
        String respuesta = f.altaCoche(this.matriculaTf.getText(), this.marcaTf.getText());
        this.mensajeLb.setText(respuesta);
    }//GEN-LAST:event_altaBtActionPerformed

    private void bajasBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajasBtActionPerformed
        /*Objeto fichero sin parámetros (Contiene toda la lectura del fichero)
        eliminamos la matricula escrita en el TextField si existe con el metodo eliminarCoche de la clase Fichero*/
        Fichero f = new Fichero();
        String mensaje = f.eliminarCoche(this.matriculaTf.getText());
        this.mensajeLb.setText(mensaje);

    }//GEN-LAST:event_bajasBtActionPerformed

    private void buscarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtActionPerformed
        /*Objeto fichero sin parámetros (Contiene toda la lectura del fichero)
        buscamos la matricula escrita en el TextField con el metodo buscar de la clase Fichero*/
        Fichero f = new Fichero();
        Coche cocheEncontrado = f.buscar(this.matriculaTf.getText());
        //Si cocheEncontrado existe
        if (cocheEncontrado != null) {
            //coge la matricula, la marca y lo pinta en el TextArea
            //coge la marca y la pinta en el TextField marca
            this.listadoTa.setText("Matricula: " + cocheEncontrado.getMatricula() + " Marca: " + cocheEncontrado.getMarca());
            this.marcaTf.setText(cocheEncontrado.getMarca());
            
        }else{
            //Si no existe deja vacío ambos TextField y en el TextArea indica que no se ha encontrado.
            this.matriculaTf.setText("");
            this.marcaTf.setText("");
            this.listadoTa.setText("Coche no encontrado");
        }
    }//GEN-LAST:event_buscarBtActionPerformed

    private void modificarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBtActionPerformed
        /*Objeto fichero sin parámetros (Contiene toda la lectura del fichero)
        buscamos la matricula escrita en el TextField con el metodo buscar de la clase Fichero*/
        Fichero f = new Fichero();
        String mensaje = f.modificarCoche(this.matriculaTf.getText(),this.marcaTf.getText());
        this.mensajeLb.setText(mensaje);
    }//GEN-LAST:event_modificarBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altaBt;
    private javax.swing.JButton bajasBt;
    private javax.swing.JButton buscarBt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listadoBt;
    private javax.swing.JTextArea listadoTa;
    private javax.swing.JLabel marcaLb;
    private javax.swing.JTextField marcaTf;
    private javax.swing.JLabel matriculaLb;
    private javax.swing.JTextField matriculaTf;
    private javax.swing.JLabel mensajeLb;
    private javax.swing.JLabel mensajeModificarLb;
    private javax.swing.JButton modificarBt;
    // End of variables declaration//GEN-END:variables
}
