
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Juan Carlos
 */
public class JuanCarlosFilterMartin extends javax.swing.JFrame {

    private ArrayList<Producto> arrayProducto = new ArrayList<>();

    /**
     * Creates new form JuanCarlosFilterMartin
     */
    public JuanCarlosFilterMartin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_drch = new javax.swing.JPanel();
        text_listado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campo_lista = new javax.swing.JTextArea();
        boton_mostrar = new javax.swing.JButton();
        boton_salir = new javax.swing.JButton();
        panel_izq = new javax.swing.JPanel();
        text_codigo = new javax.swing.JLabel();
        text_nombre = new javax.swing.JLabel();
        text_cantidad = new javax.swing.JLabel();
        text_descripcion = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        campo_codigo = new javax.swing.JTextField();
        campo_nombre = new javax.swing.JTextField();
        campo_cantidad = new javax.swing.JTextField();
        campo_descripcion = new javax.swing.JTextField();
        boton_insertar = new javax.swing.JButton();
        boton_buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_drch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        text_listado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_listado.setText("Listado de productos");

        campo_lista.setColumns(20);
        campo_lista.setRows(5);
        jScrollPane1.setViewportView(campo_lista);

        boton_mostrar.setText("Mostrar");
        boton_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_mostrarActionPerformed(evt);
            }
        });

        boton_salir.setText("Salir");
        boton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_drchLayout = new javax.swing.GroupLayout(panel_drch);
        panel_drch.setLayout(panel_drchLayout);
        panel_drchLayout.setHorizontalGroup(
            panel_drchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_drchLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panel_drchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_drchLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(boton_mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boton_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(text_listado)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panel_drchLayout.setVerticalGroup(
            panel_drchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_drchLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(text_listado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(panel_drchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_mostrar)
                    .addComponent(boton_salir))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        panel_izq.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        text_codigo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_codigo.setText("Codigo");

        text_nombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_nombre.setText("Nombre");

        text_cantidad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_cantidad.setText("Cantidad");

        text_descripcion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_descripcion.setText("Descripción");

        separador.setBackground(new java.awt.Color(255, 255, 255));
        separador.setForeground(new java.awt.Color(255, 255, 255));
        separador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        boton_insertar.setText("Insertar");
        boton_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_insertarActionPerformed(evt);
            }
        });

        boton_buscar.setText("Buscar");
        boton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_izqLayout = new javax.swing.GroupLayout(panel_izq);
        panel_izq.setLayout(panel_izqLayout);
        panel_izqLayout.setHorizontalGroup(
            panel_izqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_izqLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panel_izqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_izqLayout.createSequentialGroup()
                        .addComponent(boton_insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_izqLayout.createSequentialGroup()
                        .addGroup(panel_izqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_descripcion)
                            .addComponent(text_cantidad)
                            .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_izqLayout.createSequentialGroup()
                        .addGroup(panel_izqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_izqLayout.createSequentialGroup()
                                .addComponent(text_codigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                .addComponent(campo_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_izqLayout.createSequentialGroup()
                                .addComponent(text_nombre)
                                .addGap(54, 54, 54)
                                .addGroup(panel_izqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campo_cantidad)
                                    .addComponent(campo_nombre)
                                    .addComponent(campo_descripcion))))
                        .addGap(47, 47, 47))))
        );
        panel_izqLayout.setVerticalGroup(
            panel_izqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_izqLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(panel_izqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_codigo)
                    .addComponent(campo_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_izqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_nombre)
                    .addComponent(campo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_izqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_cantidad)
                    .addComponent(campo_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_izqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_descripcion)
                    .addComponent(campo_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_izqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_insertar)
                    .addComponent(boton_buscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_izq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_drch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_drch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_izq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Los datos se almacenarán en un fichero de texto llamado tudni.txt
     * (ejemplo 12345678T.txt), este fichero se guardará en la misma carpeta del
     * proyecto con el fín de no usar rutas absolutas.
     *
     * @param evt
     */
    private void boton_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_insertarActionPerformed
        File fichero = new File("15456141A.txt");
        //Creamos el objeto de la clase Producto con el constructor para obtener ele texto del los campos del formulario
        Producto producto = new Producto(campo_codigo.getText(), campo_nombre.getText(), campo_cantidad.getText(), campo_descripcion.getText());

        try {
            //Si el fichero no existe creamos un nuevo fichero.
            if (!fichero.exists()) {
                fichero.createNewFile();
            }
            //Escribimos en el fichero mediante el método ToString de la clase Producto y saltamos de linea.
            FileWriter fw = new FileWriter(fichero, true);
            fw.write(producto.toString());
            fw.write(System.getProperty("line.separator"));

            fw.close();
            
            JOptionPane.showMessageDialog(null, "Se ha insertador correctamente", 
                    "ÉXITO", JOptionPane.INFORMATION_MESSAGE);
            campo_codigo.setText("");
            campo_nombre.setText("");
            campo_cantidad.setText("");
            campo_descripcion.setText("");
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Se ha producido un error",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_boton_insertarActionPerformed

    private void boton_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_mostrarActionPerformed
        leerFichero("15456141A.txt");

        //Bucle for comendando en la linea 0 para que mientras el arrayProducto contenga más linea entre dentro
        //e imprima en listarProducto (hace referencia al campo_lista.setText() la linea que se encuentra  
        //posicionada el for en ese momento
        for (int i = 0; i < arrayProducto.size(); i++) {
            listarProducto(arrayProducto.get(i));
        }
    }//GEN-LAST:event_boton_mostrarActionPerformed

    private void boton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscarActionPerformed
        //Leemos el fichero mediante este método
        leerFichero("15456141A.txt");

        //Con esta variable contramos si hay error o no y poder entrar en el if con el JOptionPane
        boolean coincide = false;

        /*se crea un bucle para recorrer el arrayList Producto.
        En el array pasa por la primera linea, coge el codigo y compara con el codigo escrito en el campo_codigo del formulario. 
        Si no coincide no entra en el if, vuelve a comprobar la siguiente linea del array y si se diera el caso de que si 
        coincide entra en el if y escribe en los campos del formulario correspondiente el Codigo, nombre, cantidad y descripcion
         */
        for (int i = 0; i < arrayProducto.size(); i++) {
            if (arrayProducto.get(i).getCodigo().equals(campo_codigo.getText())) {
                coincide = true;
                campo_codigo.setText(arrayProducto.get(i).getCodigo());
                campo_nombre.setText(arrayProducto.get(i).getNombre());
                campo_cantidad.setText(arrayProducto.get(i).getCantidad());
                campo_descripcion.setText(arrayProducto.get(i).getDescripcion());
                break;
            }

        }
        if (!coincide) {
            JOptionPane.showMessageDialog(null, "Este producto no existe",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_boton_buscarActionPerformed

    private void boton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_boton_salirActionPerformed

    public void listarProducto(Producto p) {
        //Se crea una variable String productoListado para que las laista se muestré  mejor visualmente
        //mediante contatenaciones
        String productoListado = "| " + p.getCodigo() + " | "
                + p.getNombre() + " | "
                + p.getCantidad() + " | "
                + p.getDescripcion();
        //En el texArea borramos dicho recuadro y añadimos el producto listado
        campo_lista.setText(campo_lista.getText()+ productoListado + "\n");
    }

    public void leerFichero(String ruta) {

        //Hace referencia al TextArea para borrar el contenido cada vez que pulsemos en Mostrar
        campo_lista.setText("");//Elimina lo que se encuentra dentro del TextArea.
        arrayProducto.clear();     //Limpia el array

        File fichero = new File(ruta);

        try {
            //Si el fichero no existe en este  caso lo indicamos mediante un mensaje de error
            if (!fichero.exists()) {
                JOptionPane.showMessageDialog(null, "El  fichero no existe",
                        "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                //Si existe lo leemos mediante el FileReader y a su vez guardamos el contenido en memoria del bufered
                FileReader fd = new FileReader(fichero);
                BufferedReader bf = new BufferedReader(fd);

                //El bufferedReader se posiciona en la primera linea la lee y la devuelve a la variable linea
                String linea = bf.readLine();

                //Mientras linea no sea null ejecuta lo que hay dentro del while
                while (linea != null) {
                    //La variable linea  que contiene la linea completa la almacenaremos en el array
                    //Cada posicion del array va separada del string con el ":" 
                    String[] producto = linea.split(": ");
                    //Se crea un objeto de la clase producto almacenandole el  array recien creado e 
                    //introduciendo en cada posicion correspondiente
                    Producto p = new Producto(producto[0], producto[1], producto[2], producto[3]);

                    //añadimos el objeto producto al ArrayList arrayProducto y el bufferedReader se 
                    //posiciona en la siguiente linea y la devuelve a la variable linea
                    arrayProducto.add(p);
                    linea = bf.readLine();
                }
                fd.close();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Se ha producido un error",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuanCarlosFilterMartin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuanCarlosFilterMartin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuanCarlosFilterMartin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuanCarlosFilterMartin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuanCarlosFilterMartin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_buscar;
    private javax.swing.JButton boton_insertar;
    private javax.swing.JButton boton_mostrar;
    private javax.swing.JButton boton_salir;
    private javax.swing.JTextField campo_cantidad;
    private javax.swing.JTextField campo_codigo;
    private javax.swing.JTextField campo_descripcion;
    private javax.swing.JTextArea campo_lista;
    private javax.swing.JTextField campo_nombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_drch;
    private javax.swing.JPanel panel_izq;
    private javax.swing.JSeparator separador;
    private javax.swing.JLabel text_cantidad;
    private javax.swing.JLabel text_codigo;
    private javax.swing.JLabel text_descripcion;
    private javax.swing.JLabel text_listado;
    private javax.swing.JLabel text_nombre;
    // End of variables declaration//GEN-END:variables
}
