/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package U5_11_JRadioButtonJCheckBox;

import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Juan Carlos
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbgroup = new javax.swing.ButtonGroup();
        sistemaoperativoLb = new javax.swing.JLabel();
        windowsRb = new javax.swing.JRadioButton();
        ubuntuRb = new javax.swing.JRadioButton();
        macRb = new javax.swing.JRadioButton();
        generarBt = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        programacionCb = new javax.swing.JCheckBox();
        disenoCb = new javax.swing.JCheckBox();
        administracionCb = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        especilidadLb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Requisistos de Sistemas Operativos");

        sistemaoperativoLb.setText("Elige un sistema operativo");

        rbgroup.add(windowsRb);
        windowsRb.setText("Windows");

        rbgroup.add(ubuntuRb);
        ubuntuRb.setText("Ubuntu");

        rbgroup.add(macRb);
        macRb.setText("Mac");

        generarBt.setText("Generar");
        generarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarBtActionPerformed(evt);
            }
        });

        programacionCb.setText("Programación");

        disenoCb.setText("Diseño");

        administracionCb.setText("Administración");

        especilidadLb.setText("Elige tu especilidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(especilidadLb)
                                    .addComponent(administracionCb)
                                    .addComponent(disenoCb)
                                    .addComponent(programacionCb)
                                    .addComponent(sistemaoperativoLb)
                                    .addComponent(ubuntuRb)
                                    .addComponent(macRb)
                                    .addComponent(windowsRb)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(generarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 60, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(sistemaoperativoLb)
                .addGap(18, 18, 18)
                .addComponent(windowsRb)
                .addGap(18, 18, 18)
                .addComponent(ubuntuRb)
                .addGap(18, 18, 18)
                .addComponent(macRb)
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(especilidadLb)
                .addGap(18, 18, 18)
                .addComponent(programacionCb)
                .addGap(18, 18, 18)
                .addComponent(disenoCb)
                .addGap(18, 18, 18)
                .addComponent(administracionCb)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(generarBt)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarBtActionPerformed
         String informacion="Tu sistema operativo preferido es ";
        
        //Cogemos todos los radiobutton en un array
        JRadioButton[] rdbs={windowsRb,ubuntuRb,macRb};
        
        for(int i=0;i<rdbs.length;i++){
            
            //Si esta seleccionado, coge el texto
            if(rdbs[i].isSelected()){
                informacion+=rdbs[i].getText();
            }
            
        }
        
        //Hacemos igual con los checkboxes
        JCheckBox[] ckbs={programacionCb,disenoCb,administracionCb};
        
        informacion+=" \nTus especialidades son ";
        
        for(int i=0;i<ckbs.length;i++){
            
            if(ckbs[i].isSelected()){
                informacion+=ckbs[i].getText()+" "; //Ponemos un espacio por si hay mas de un elemento seleccionado
            }
            
        }
        

        
        JOptionPane.showMessageDialog(this, informacion, "Muestra de datos", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_generarBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox administracionCb;
    private javax.swing.JCheckBox disenoCb;
    private javax.swing.JLabel especilidadLb;
    private javax.swing.JButton generarBt;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton macRb;
    private javax.swing.JCheckBox programacionCb;
    private javax.swing.ButtonGroup rbgroup;
    private javax.swing.JLabel sistemaoperativoLb;
    private javax.swing.JRadioButton ubuntuRb;
    private javax.swing.JRadioButton windowsRb;
    // End of variables declaration//GEN-END:variables
}
